[PR - ISSUE #1] 게시판 CRUD
f-lab-edu/KLeagueFanSite pull request #3
Opened 2023-11-16 06:48 UTC by KimJunyoung

2023.11.16 시작

게시판 기능

- [ ] 글 작성
- [ ] 글 수정
- [ ] 글 조회
- [ ] 글 삭제

게시판 기능 구현을 하고 회원가입/로그인 구현으로 넘어갈 생각입니다..

현재는 Branch 를 feature/ISSUE-1-BoradCrud 로 해뒀는데 CRUD 마다 Branch 를 만들어 주는게 좋은건지 모르겠습니다.

2023-11-19 14:21 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
코멘트를 좀 남겨 봤는데 확인 후 다시 푸시 해주세요 ~

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/domain/Post.java
> +    public PostModifier.PostModifierBuilder modifierBuilder() {
[클린 아키텍처](https://daryeou.tistory.com/280)를 참고 해 보시면 좋을 것 같아요 ~ 의존성 방향은 바깥에서 안쪽으로 향해야 합니다. Request에서의 필드명이 바뀌거나 다른 서비스에서 같은 도메인을 쓴다고 할 때, 그 변경이 이 도메인에까지 영향을 미쳐야 하나? 를 고민해보시면 좋을 것 같아요 ~

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/exception/NoValueException.java
> +@ResponseStatus(value = HttpStatus.NOT_FOUND )
Exception에 따로 정의를 하기보단 `@ExceptionHandler`를 이용하는 방법을 찾아보시면 좋을 것 같아요 ~

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/repository/CustomRepository.java
> +public interface CustomRepository {
커스텀한 인터페이스가 하나만 필요하지 않을텐데, 도메인이 같이 드러나는게 좋을 것 같아요 ~

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/repository/CustomRepositoryImpl.java
> +                .where(post.title.contains(postSearch.getTitle())
contains는 쿼리가 어떻게 나가게 될까요 ?

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/repository/CustomRepositoryImpl.java
> +                .offset(postSearch.getOffSet())
offset 방식을 사용하는 경우 페이지 번호가 높아질수록 성능이 안좋아지는 현상이 발생할 수 있는데 왜그럴까요 ?

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/request/PostCreate.java
> +public class PostCreate {
DTO는 Request / Response 정도는 명시해주면 좋을 것 같아요 ~

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/request/PostCreate.java
> +@Setter
getter/setter 의 사용은 지양하고 있습니다. 왜 지양해야 하는지 알아보시면 좋을 것 같아요 ~

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/request/PostModifier.java
> +     *  Modify(null Check) 를 위한 Builder 수동 구현
`@Builder` 를 사용하면 null 체크를 할 수 없나요 ?

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/request/PostModify.java
> +public class PostModify {
Modify랑 Modifier가 무슨차이가 있는거에요 ?

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/request/PostSearch.java
> +    @Builder.Default
요청에 값이 없는 경우의 기본값일텐데 .. 이거 원하는대로 동작 하나요 ?

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/response/PostResponse.java
> +@Data
`@Data`도 사용하면 안되는 이유를 찾아보면 좋을 것 같아요 ~

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/service/PostService.java
> +@Transactional(readOnly = true)
클래스 레벨에 설정해둬서 기본값처럼 사용하는것도 좋지만, 개인적으로는 어차피 메서드에 명시되어 있지 않으면 클래스 레벨까지 찾아봐야 하는 단점이 있어서 그냥 메서드 각각에 선언하는걸 선호합니다 ~

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/service/PostService.java
> +        Post post = postRepository.findById(postId).orElseThrow(NoValueException::new);
예외에 전달받은 id가 뭐였고, 뭐가 없는건지 정확히 나타내주면 좋을 것 같아요 ~

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/service/PostService.java
> +    private static PostResponse getPostResponse(Post post) {
Response를 만들고 있어서 get은 부적절한 것 같아요 ~ 그리고 생성의 책임은 PostResponse가 가져가도 되지 않을까요 ?

2023-11-19 14:21 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/service/PostService.java
> +                .map(post -> PostResponse.builder()
여기는 아래 메서드가 있는데 중복 선언되는 것 같네요 ~

2023-11-20 02:40 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/controller/PostController.java
> +@RequiredArgsConstructor
제가 생각하는 단점입니다. 
1. final 선언을 해줘야만 생성자 변수에 포함됩니다.
2. 같은 타입 int cat, int dog 순서를 바꿔도 사용자 입장에서는 모를 수 있습니다. 그래서 예상과 다른 값이 입력될 수 있습니다.

2023-11-20 03:37 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/domain/Post.java
> +    public Post() {
넵!

2023-11-20 03:44 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/request/PostCreate.java
> +@Setter
넵 알겠습니다 :) 
Getter 에 대해 궁금한게 있습니다.
1. DTO 는 전달을 위한 객체일 뿐인데 Getter 를 사용해도 괜찮지 않을까요 ?
2. @RequestBody @ResponseBody 사용 시 Jackson 라이브러리를 통해 Getter 사용해서 Json 으로 직렬화/역직렬화를 해준다고 알고있는데 Getter 를 사용하지 않고 어떻게 해야할 지 생각이 나지 않습니다 😢

2023-11-20 03:51 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/request/PostModify.java
> +public class PostModify {
Modify 는 클라이언트가 수정하고 싶은 내용을 담은 DTO 객체 입니다.
Modifier 는 Post domain 수정을 위한 객체 입니다.

1. ModifyRequest
2. Service단에서 Post 기존 값을 가진 Post PostModifier.PostModifierBuilder 생성 
3. PostModifierBuilder 의 title, content 값을 ModifyRequest 의 title, content 값으로 변경 후 build -> PostModifier 생성
4. Post.modify 의 매개변수에 PostModifier 를 넘겨 줌
5. Post 에선 title, content 값을 PostModifier 객체의 title, content 값으로 수정 

위와 같이 글 수정을 구현하고 있습니다.

2023-11-20 03:51 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/response/PostResponse.java
> +@Data
넵!

2023-11-20 03:52 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/service/PostService.java
> +        Post post = postRepository.findById(postId).orElseThrow(NoValueException::new);
네 ! ExceptionHandler 사용 하면서 같이 구현하도록 하겠습니다!

2023-11-20 03:58 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/service/PostService.java
> +    private static PostResponse getPostResponse(Post post) {
중복을 피하기 위해서 중복되는 PostResponse 생성에 관한 내용을 메서드로 묶었었습니다.
말씀해주신 대로 생성의 책임은 PostResponse 가 가지는게 객체지향 관점에서 더 옳은 것 같습니다.

2023-12-07 14:52 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
코멘트를 좀 남겨 뒀는데, 머지 이후 고민해보셔도 될 것 같아요 ~

2023-12-07 14:52 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/exception/MainException.java
> +    List<ValidationTuple> validationTupleList = new ArrayList<>();
음 .. Exception은 타입과 메세지 만으로도 많은 걸 전달 할 수 있어서 굳이 요런 구조가 필요할까 싶네요! 괜히 예외 만드는 작업만 힘들어지지 않을까 해서요 ~

2023-12-07 14:52 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/service/PostService.java
> +        Post post = postRepository.findById(postId).orElseThrow(() -> new NoIdValueException(postId, "Post"));
예외 발생한 상황을 자세하게 적어주는게 더 도움이 될 것 같고, 나중에 로그로 어떤 부분에서 예외가 발생한건지 찾기도 쉬울 것 같아요
보통 `[클래스 명] 발생 이유 (요청을 식별할 수 있는 필드)` 요런 느낌으로 많이 작성합니다

2023-12-07 14:52 UTC, f-lab-moony commented on src/test/java/com/kleague/kleaguefinder/controller/PostControllerTest.java
> +    public void testV4() throws Exception {
`@DisplayName` 으로 구분 하더라도 메서드명은 그냥 실제 테스트하는 메서드에서 따오는게 좋을 것 같아요 ~

2023-12-08 00:07 UTC, merged