[PR - ISSUE #2] 축구 예매 기능 구현
f-lab-edu/KLeagueFanSite pull request #5
Opened 2023-12-07 06:38 UTC by KimJunyoung

축구 예매 기능 구현 Pull Request.

Commit 설명
[[feature/ISSUE-2-Reservation]GameInfo Service, Controller and Test]]
1. 기본적인 GameInfo 에 대한 Crud 구현
2. Service Test 구현

[[feature/ISSUE-2-Reservation] GameInfo Exception]
1. Exception 을 해당 예외에 맞게 만들고 ControllerAdvice 사용해서 잡아줌
2. Controller Test 

[[feature/ISSUE-2-Reservation]Exception and Validation]
1. 컨트롤러 단에서 @Valid 로 Request Null 등 체크
2. ErrorResponse message 가 여러개 나올 수 있기 때문에 List<String> 으로 저장
3. 그에 따른 테스트 변경 및 수행 

앞으로

- [ ] Seat 에 대한 기능 구현을 먼저 한 후 Reservation, ReservedSeat 에 관한 비즈니스 로직 구현 
- [ ] 중복 예외인 DuplicateException 에 Field 값을 넣을 때 두개를 넣기 위해 변경이 필요함 (현재는 String 으로 "name & location" 으로 표현)
- [ ] Seat 엔티티에 어떤 속성이 필요한지 생각해보자.

2023-12-07 16:11 UTC, f-lab-moony requested changes
고생하셨습니다!
코멘트를 좀 남겨 뒀는데, 확인 부탁드려요 ~

2023-12-08 00:37 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/domain/Category.java
> +    A,B,C
좌석의 등급을 나타낼려고 사용했습니다.

2023-12-08 00:38 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/domain/Reservation.java
> +    private Seat seat;
맞네요.. 🤣

2023-12-08 00:39 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/domain/Reservation.java
> +    private LocalDateTime localDateTime;
예약을 완료했을 때 시간을 나타내려고 했습니다! 명확히 표현할게요

2023-12-08 00:39 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/domain/Reservation.java
> +    private String name;
알겠습니다 !

2023-12-08 00:45 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/domain/Reservation.java
> +        seat.changeReservation(this);
그러면 결국 예약에 따라 다시 다 만들어줘야하는 것 같습니다.
그럼 예약정보에서만 좌석을 가지고 있도록 단방향으로 설정하는게 맞을 것 같습니다.

2023-12-08 00:45 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/request/GameInfoRequestDto.java
> +public class GameInfoRequestDto {
게시판 만들때는 DTO 를 붙이지 않고 했으면서, 여기서는 붙였네요.. 명심하도록 하겠습니다.

2023-12-17 13:40 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~
이번 작업은 바로 머지 해 둘게요~

2023-12-17 13:40 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/controller/GameInfoController.java
> +@RequiredArgsConstructor
이것도 `@AllArgsConstructor` 처럼 사용을 지양하는 어노테이션이에요 ~

2023-12-17 13:40 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/controller/GameInfoController.java
> +    @PostMapping("api/v1/gameInfo/save")
별거 아닌거처럼 보일수도 있겠지만 컨벤션이란게 꽤 중요해서 ..
`api/v1/gameInfos`처럼 도메인의 복수형으로 표현해주고, 아이디가 필요한경우는 pathVariable로 id를, 아닌 경우는 그냥 비워두시고 RequestBody나 RequestParam 받으시면 될거같아요 ~
save / search 이런건 드러내지 않아도 괜찮아요 어차피 메서드 타입으로 구분이 돼서 ..

아 밑에도 있지만 예외적으로 Post는 조회에도 쓰이는데 그것도 그냥 무시하고 굳이 안드러내도 상관 없습니다 ~

2023-12-17 13:40 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/controller/GameInfoController.java
> +    @PostMapping("api/v1/gameInfo/save")
다른 도메인의 아이디가 필요한경우는 `/by-seat-number` 이런식으로 사용해요!

2023-12-17 13:40 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/controller/exception/ExceptionController.java
> +    public List<String> makeMessage(MethodArgumentNotValidException e) {
개인적으로 메세지 여기서 만드는건 별로 좋지 못한 방법인 것 같아요
로그라는건 결국 문제가 생겼을때 트래킹을 하기 위해 필요한건데, 만드는 부분이 공통화가 되어있으면 찾기가 좀 어렵지 않을까 싶습니다. 왠만하면 로그 메세지는 조작을 최대한 덜 하는게 좋을 것 같아요 ~

2023-12-17 13:40 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/repository/gameinfo/GameInfoCustomRepository.java
> +    List<GameInfo> findByRequest(GameInfoSearchRequest request);
도메인 레이어에서 view 레이어에 의존성이 생기는건 안좋아요. 써야하는 파라미터를 추출해서 따로 만들어주는게 좋을 것 같아요

2023-12-17 13:40 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/request/gameinfo/GameInfoSearchRequest.java
> +@Builder
`@Builder` 는 클래스에 선언하는것보다 생성자에 선언하는게 좋아요 ~

만드는 방식이 다른 두 개의 빌더가 필요할 때, 클래스에 선언하면 조작도 어렵고 예기치 못한 동작을 할 수가 있어요

2023-12-17 13:40 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/response/GameInfoResponse.java
> +{
자바 구글 컨벤션 + save action 플러그인 적용해보면 좋을 것 같아요 ~

2023-12-17 13:40 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/domain/GameInfo.java
> +        this.date = date;
요거 date는 왜 string인가요 ?

2023-12-17 13:40 UTC, f-lab-moony commented on src/main/java/com/kleague/kleaguefinder/service/GameInfoService.java
> +        GameInfo gameInfo = gameInfoRepository.findById(gameInfoId)
orElseThrow 하는 부분까지 따로 메서드로 추출할 수 있을 것 같아요 ~

2023-12-17 13:40 UTC, f-lab-moony commented on src/test/java/com/kleague/kleaguefinder/controller/GameInfoControllerTest.java
> +        gameInfoRepository.saveAll(gameInfoList);
저번에 말씀드리긴 했지만, 이런 작업은 Service를 목킹하면 안해도 될 것 같아요 ~

2023-12-17 13:40 UTC, f-lab-moony commented on src/test/java/com/kleague/kleaguefinder/controller/GameInfoControllerTest.java
> +        mockMvc.perform(post("/api/v1/gameInfo/save")
굳이 따지자면 얘가 when 같은데 .. when과 then이 나누기 어려울 땐 expect라고 표현해요 ~

2023-12-17 13:40 UTC, f-lab-moony commented
뭔가 이전 작업이랑 컨플릭이 나는 것 같은데, 준영님이 해결 후 머지 눌러주세요 ~

2023-12-18 05:06 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/controller/GameInfoController.java
> +    @PostMapping("api/v1/gameInfo/save")
넵 알겠습니다. 수정하고 다음부터 작성할 땐 유의해서 작업하겠습니다

2023-12-18 08:17 UTC, merged

2023-12-19 00:24 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/controller/exception/ExceptionController.java
> +    public List<String> makeMessage(MethodArgumentNotValidException e) {
궁금한 점이 많아서 멘토링 시간에 여쭤보겠습니다.

2023-12-19 00:36 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/domain/GameInfo.java
> +        this.date = date;
처음에 만들 때 다루기 쉬워서 String 으로 하고 나중에 바꿔야지 했는데 
그렇게 하면 일이 두배로 는다는 것을 이번에 느꼈습니다.. 🥲

2023-12-19 00:40 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/repository/gameinfo/GameInfoCustomRepository.java
> +    List<GameInfo> findByRequest(GameInfoSearchRequest request);
파라미터가 5~6개 정도 되는 경우는 DTO 를 만드는건 어떨까요 ?

2023-12-19 00:48 UTC, KimJunyoung commented on src/main/java/com/kleague/kleaguefinder/repository/gameinfo/GameInfoCustomRepository.java
> +    List<GameInfo> findByRequest(GameInfoSearchRequest request);
넵 알겠습니다. DTO 사용 범위를 찾아보겠습니다.

2023-12-19 03:03 UTC, KimJunyoung commented on src/test/java/com/kleague/kleaguefinder/controller/GameInfoControllerTest.java
> +        gameInfoRepository.saveAll(gameInfoList);
옙 ! 찾아보고 적용시켜 보겠습니다.